pipeline {
    agent any

    environment {
        CI = 'true'
    }

    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Deliver') { 
            steps {
                sh 'set -x #echo on'
                sh 'nohup npm start > log.txt&'
                sh 'image node:6-alpine' 
                sh ' args -p 3000:3000'
                sh 'sleep 1'
                sh 'echo $! > .pidfile'
                sh 'set +x'
            }
        }
    }
}
