pipeline {
    agent any

       stages {
                stage('Build') {
                    steps {
                        sh('react\\my-app') {
                            sh 'Start building process...'
                            sh 'npm install'
                        }
                    }
                }
                stage('Test') {
                    steps {
                        sh 'Testing.. //TODO run automation tests...'
                    }
                }
                stage('Deploy') {
                     steps {
                        sh 'Deployment steps.. //TODO copy build file to target folder...'
                    }
                }
            }
   
            post { 
                success {  
                    sh('react\\my-app') {
                            sh 'npm start'
                        }
                }
            }
        }
   

